/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arayuzler;

import Kitap.*;

import System.InfoKullanici;
import System.InfoKitap;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Giris extends javax.swing.JFrame {

    /**
     * Creates new form Giris
     */
    public Giris() throws IOException {
        initComponents();
          InfoKullanici.Admin_Olustur();  
          InfoKullanici.Kullanici_Olustur();
        InfoKitap.KitaplariOlustur();
         
                 
    }
Admin_GUI adminPanel;
 Kullanici_GUI kullaniciPanel; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpAnapanel = new javax.swing.JPanel();
        jrAdmin = new javax.swing.JRadioButton();
        jrKullanici = new javax.swing.JRadioButton();
        lblParola = new javax.swing.JLabel();
        lblKullaniciID = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtbnGiris = new javax.swing.JButton();
        jtpPasswd = new javax.swing.JPasswordField();
        jcParolaGoster = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giris");

        jpAnapanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(jrAdmin);
        jrAdmin.setText("Admin Girişi");
        jrAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrKullanici);
        jrKullanici.setText("Kullanici Girişi");
        jrKullanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrKullaniciActionPerformed(evt);
            }
        });

        lblParola.setText("Kullanici Parola :");

        lblKullaniciID.setText("Kullanici ID :");

        jtbnGiris.setText("GIRIS");
        jtbnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnGirisActionPerformed(evt);
            }
        });

        jcParolaGoster.setText("ParolaGoster");
        jcParolaGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcParolaGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAnapanelLayout = new javax.swing.GroupLayout(jpAnapanel);
        jpAnapanel.setLayout(jpAnapanelLayout);
        jpAnapanelLayout.setHorizontalGroup(
            jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAnapanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAnapanelLayout.createSequentialGroup()
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcParolaGoster)
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addComponent(jrAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrKullanici)))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAnapanelLayout.createSequentialGroup()
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAnapanelLayout.createSequentialGroup()
                                .addComponent(lblParola, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addComponent(lblKullaniciID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtpPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jtfID))
                        .addGap(135, 135, 135))))
            .addGroup(jpAnapanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jtbnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAnapanelLayout.setVerticalGroup(
            jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnapanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrAdmin)
                    .addComponent(jrKullanici))
                .addGap(36, 36, 36)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtpPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParola, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcParolaGoster)
                .addGap(4, 4, 4)
                .addComponent(jtbnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAnapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAnapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAdminActionPerformed
        // TODO add your handling code here:
        if (jrAdmin.isSelected()) {
            lblKullaniciID.setText("Admin ID :");
            lblParola.setText("Admin Parola :");
        }
        else if(jrKullanici.isSelected()){
            
            lblKullaniciID.setText("Kullanici ID :");
            lblParola.setText("Kullanici Parola :");
        }
    }//GEN-LAST:event_jrAdminActionPerformed

    public String BaglananKullaniciID(){
        return jtfID.getText();
    }
    public String BaglananKullaniciParola(){
        String x = String.valueOf(jtpPasswd.getPassword());
        return x;
    }
    private void jrKullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrKullaniciActionPerformed
        if (jrAdmin.isSelected()) {
            lblKullaniciID.setText("Admin ID :");
            lblParola.setText("Admin Parola :");
        }
        else if(jrKullanici.isSelected()){
            
            lblKullaniciID.setText("Kullanici ID :");
            lblParola.setText("Kullanici Parola :");
        }
    }//GEN-LAST:event_jrKullaniciActionPerformed

    private void jcParolaGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcParolaGosterActionPerformed
        if (jcParolaGoster.isSelected()) {
          
           jtpPasswd.setEchoChar((char)0) ;
        }
        else
          jtpPasswd.setEchoChar('*');   
    }//GEN-LAST:event_jcParolaGosterActionPerformed
    public static String GirilenSifre = "";
    public static String GirilenID = "";
    private void jtbnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnGirisActionPerformed
      
        if (jrAdmin.isSelected()) {
            String pass = String.valueOf(jtpPasswd.getPassword());
            if (InfoKullanici.Admin_Giris(jtfID.getText(), pass)) {
                GirilenID = jtfID.getText();
                GirilenSifre = pass;
              adminPanel = new Admin_GUI(this);
              adminPanel.setVisible(true);
              this.setVisible(false);
              this.setVisible(false);
              
            }
    
            
        }
        else{
           
            String pass = String.valueOf(jtpPasswd.getPassword());
            if (InfoKullanici.Kullanici_Giris(jtfID.getText(), pass)) {
                GirilenID = jtfID.getText();
                GirilenSifre = pass;
                kullaniciPanel = new Kullanici_GUI(this);
                kullaniciPanel.setVisible(true);
              this.setVisible(false);
              this.setVisible(false); 
            }
            
        }
        
    }//GEN-LAST:event_jtbnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Giris().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jcParolaGoster;
    private javax.swing.JPanel jpAnapanel;
    private javax.swing.JRadioButton jrAdmin;
    private javax.swing.JRadioButton jrKullanici;
    private javax.swing.JButton jtbnGiris;
    private javax.swing.JTextField jtfID;
    private javax.swing.JPasswordField jtpPasswd;
    private javax.swing.JLabel lblKullaniciID;
    private javax.swing.JLabel lblParola;
    // End of variables declaration//GEN-END:variables
}
