/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arayuzler;

import Kitap.*;
import Kullanici.Normal;
import System.InfoKitap;
import System.InfoKullanici;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OGUZ
 */
public class Kullanici_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Kullanici_GUI
     */
      public Kitap secilen;
      String BaglananID;
      String BaglananSifre;
      Giris a;
    public Kullanici_GUI(Giris x) {
        initComponents();
        a = x;
        Panaller.setVisible(false);
        jpKitapList.setVisible(false);
       // ImageIcon image = new ImageIcon("C:\\Users\\OGUZ\\Desktop\\YkRJ.gif");
        //jLabel1.setIcon(image);
        kitap = InfoKitap.getKitapListem();
       basili = InfoKitap.getBasili();
       elek = InfoKitap.getEkitap();
       roman = InfoKitap.getRomans();
       dergi = InfoKitap.getDergi();
       ansiklopedi = InfoKitap.getAnsiklopedi();
      jpanelSecimler.setVisible(false);
      
     BaglananID = x.BaglananKullaniciID();
     BaglananSifre = x.BaglananKullaniciParola();
     
    }
 ArrayList<Kitap> kitap;
    ArrayList<BasiliKitap>basili;
    ArrayList<E_Kitap>elek;
    ArrayList<Roman>roman;
    ArrayList<Dergi>dergi;
    ArrayList<Ansiklopedi>ansiklopedi;
    DahaFazla daha;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupArama = new javax.swing.ButtonGroup();
        jpAnaPanel = new javax.swing.JPanel();
        Panaller = new javax.swing.JPanel();
        jpKitapList = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelShowAll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKitap = new javax.swing.JTable();
        panelShowBasili = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBasili = new javax.swing.JTable();
        panelShowEKitap = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEkitap = new javax.swing.JTable();
        panelShowRoman = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRoman = new javax.swing.JTable();
        panelShowAnsiklopedi = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableAnsiklopedi = new javax.swing.JTable();
        panelShowDergi = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableDergi = new javax.swing.JTable();
        btnDahaFazlaBilg = new javax.swing.JButton();
        jpAramaPanelleri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrKitapIDARA = new javax.swing.JRadioButton();
        jrKitapADIARA = new javax.swing.JRadioButton();
        jpanelSecimler = new javax.swing.JPanel();
        PanelIDileAra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfSearchedId = new javax.swing.JTextField();
        panelAdİleAra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfSearchedName = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableAranan = new javax.swing.JTable();
        btnAra = new javax.swing.JButton();
        btnOduncAL = new javax.swing.JButton();
        lblMesaj = new javax.swing.JLabel();
        jPMevcutKitaplar = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableMevcutKitaplar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDAHAFAZLAMEVCUT = new javax.swing.JButton();
        jPHesabim = new javax.swing.JPanel();
        jpSifreDegis = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPassEskiKullaniciSifre = new javax.swing.JPasswordField();
        jPassYeniKullaniciSifre = new javax.swing.JPasswordField();
        jPassYeniKullaniciSifre2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanici Panel");

        jpAnaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Panaller.setLayout(new java.awt.CardLayout());

        jpKitapList.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));

        panelShowAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelShowAllMouseClicked(evt);
            }
        });
        panelShowAll.setLayout(new javax.swing.OverlayLayout(panelShowAll));

        tableKitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kitap Adi", "Yayin Evi", "Basim Tarihi"
            }
        ));
        jScrollPane1.setViewportView(tableKitap);

        panelShowAll.add(jScrollPane1);

        jTabbedPane1.addTab("Tüm", panelShowAll);

        panelShowBasili.setLayout(new javax.swing.OverlayLayout(panelShowBasili));

        tableBasili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kitap Adi", "Yayin Evi", "Basim Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableBasili);

        panelShowBasili.add(jScrollPane2);

        jTabbedPane1.addTab("Basili", panelShowBasili);

        panelShowEKitap.setLayout(new javax.swing.OverlayLayout(panelShowEKitap));

        tableEkitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kitap Adi", "Yayin Evi", "Basim Tarihi", "Dil"
            }
        ));
        jScrollPane3.setViewportView(tableEkitap);

        panelShowEKitap.add(jScrollPane3);

        jTabbedPane1.addTab("E-Kitap", panelShowEKitap);

        panelShowRoman.setLayout(new javax.swing.OverlayLayout(panelShowRoman));

        tableRoman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kitap Adi", "Yayin Evi", "Basim Tarihi", "Yazar", "Tür"
            }
        ));
        jScrollPane4.setViewportView(tableRoman);

        panelShowRoman.add(jScrollPane4);

        jTabbedPane1.addTab("Roman", panelShowRoman);

        panelShowAnsiklopedi.setLayout(new javax.swing.OverlayLayout(panelShowAnsiklopedi));

        tableAnsiklopedi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kitap Adi", "Yayin Evi", "Basim Tarihi", "Konu"
            }
        ));
        jScrollPane5.setViewportView(tableAnsiklopedi);

        panelShowAnsiklopedi.add(jScrollPane5);

        jTabbedPane1.addTab("Ansiklopedi", panelShowAnsiklopedi);

        panelShowDergi.setLayout(new javax.swing.OverlayLayout(panelShowDergi));

        tableDergi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kitap Adi", "Yayin Evi", "Basim Tarihi", "Tür", "Editor"
            }
        ));
        jScrollPane6.setViewportView(tableDergi);

        panelShowDergi.add(jScrollPane6);

        jTabbedPane1.addTab("Dergi", panelShowDergi);

        btnDahaFazlaBilg.setText("Daha Fazla Bilgi");
        btnDahaFazlaBilg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDahaFazlaBilgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpKitapListLayout = new javax.swing.GroupLayout(jpKitapList);
        jpKitapList.setLayout(jpKitapListLayout);
        jpKitapListLayout.setHorizontalGroup(
            jpKitapListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKitapListLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpKitapListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDahaFazlaBilg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jpKitapListLayout.setVerticalGroup(
            jpKitapListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKitapListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDahaFazlaBilg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Panaller.add(jpKitapList, "card2");

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hangi Yol Ile Arayacaksin ?");

        buttonGroupArama.add(jrKitapIDARA);
        jrKitapIDARA.setText("Kitap ID");
        jrKitapIDARA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrKitapIDARAActionPerformed(evt);
            }
        });

        buttonGroupArama.add(jrKitapADIARA);
        jrKitapADIARA.setText("Kitap Adi");
        jrKitapADIARA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrKitapADIARAActionPerformed(evt);
            }
        });

        jpanelSecimler.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID : ");

        javax.swing.GroupLayout PanelIDileAraLayout = new javax.swing.GroupLayout(PanelIDileAra);
        PanelIDileAra.setLayout(PanelIDileAraLayout);
        PanelIDileAraLayout.setHorizontalGroup(
            PanelIDileAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIDileAraLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSearchedId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        PanelIDileAraLayout.setVerticalGroup(
            PanelIDileAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIDileAraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIDileAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSearchedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelSecimler.add(PanelIDileAra, "card2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kitap Adi :");

        javax.swing.GroupLayout panelAdİleAraLayout = new javax.swing.GroupLayout(panelAdİleAra);
        panelAdİleAra.setLayout(panelAdİleAraLayout);
        panelAdİleAraLayout.setHorizontalGroup(
            panelAdİleAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdİleAraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSearchedName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelAdİleAraLayout.setVerticalGroup(
            panelAdİleAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdİleAraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdİleAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSearchedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jpanelSecimler.add(panelAdİleAra, "card3");

        tableAranan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adi :", "Yayin Evi :", "Tür :", "Konu :"
            }
        ));
        jScrollPane8.setViewportView(tableAranan);

        btnAra.setText("ARA");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        btnOduncAL.setText("ODUNC AL");
        btnOduncAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncALActionPerformed(evt);
            }
        });

        lblMesaj.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpAramaPanelleriLayout = new javax.swing.GroupLayout(jpAramaPanelleri);
        jpAramaPanelleri.setLayout(jpAramaPanelleriLayout);
        jpAramaPanelleriLayout.setHorizontalGroup(
            jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                .addGroup(jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                                .addComponent(jrKitapIDARA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrKitapADIARA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180))))
                    .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpanelSecimler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                                .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnOduncAL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpAramaPanelleriLayout.setVerticalGroup(
            jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAramaPanelleriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrKitapADIARA)
                    .addComponent(jrKitapIDARA))
                .addGap(24, 24, 24)
                .addGroup(jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelSecimler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpAramaPanelleriLayout.createSequentialGroup()
                        .addGroup(jpAramaPanelleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOduncAL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMesaj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        Panaller.add(jpAramaPanelleri, "card3");

        jTableMevcutKitaplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adi", "Kitap Türü", "Konu", "Teslim Tarihi"
            }
        ));
        jScrollPane7.setViewportView(jTableMevcutKitaplar);

        jButton1.setText("IADE ET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDAHAFAZLAMEVCUT.setText("DAHA FAZLA BİLGİ");
        btnDAHAFAZLAMEVCUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDAHAFAZLAMEVCUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMevcutKitaplarLayout = new javax.swing.GroupLayout(jPMevcutKitaplar);
        jPMevcutKitaplar.setLayout(jPMevcutKitaplarLayout);
        jPMevcutKitaplarLayout.setHorizontalGroup(
            jPMevcutKitaplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMevcutKitaplarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMevcutKitaplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMevcutKitaplarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addContainerGap())
            .addGroup(jPMevcutKitaplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPMevcutKitaplarLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(btnDAHAFAZLAMEVCUT, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        jPMevcutKitaplarLayout.setVerticalGroup(
            jPMevcutKitaplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMevcutKitaplarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(jPMevcutKitaplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPMevcutKitaplarLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(btnDAHAFAZLAMEVCUT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );

        Panaller.add(jPMevcutKitaplar, "card4");

        javax.swing.GroupLayout jPHesabimLayout = new javax.swing.GroupLayout(jPHesabim);
        jPHesabim.setLayout(jPHesabimLayout);
        jPHesabimLayout.setHorizontalGroup(
            jPHesabimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        jPHesabimLayout.setVerticalGroup(
            jPHesabimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        Panaller.add(jPHesabim, "card5");

        jLabel4.setText("YENİ SİFRE :");

        jLabel5.setText("YENİ SİFRE :");

        jLabel6.setText("ESKİ SİFRE :");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("SİFRE DEGİS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSifreDegisLayout = new javax.swing.GroupLayout(jpSifreDegis);
        jpSifreDegis.setLayout(jpSifreDegisLayout);
        jpSifreDegisLayout.setHorizontalGroup(
            jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSifreDegisLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpSifreDegisLayout.createSequentialGroup()
                        .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassYeniKullaniciSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jPassEskiKullaniciSifre)
                            .addComponent(jPassYeniKullaniciSifre2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jpSifreDegisLayout.setVerticalGroup(
            jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSifreDegisLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassEskiKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassYeniKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassYeniKullaniciSifre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        Panaller.add(jpSifreDegis, "card6");

        javax.swing.GroupLayout jpAnaPanelLayout = new javax.swing.GroupLayout(jpAnaPanel);
        jpAnaPanel.setLayout(jpAnaPanelLayout);
        jpAnaPanelLayout.setHorizontalGroup(
            jpAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnaPanelLayout.createSequentialGroup()
                .addComponent(Panaller, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpAnaPanelLayout.setVerticalGroup(
            jpAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnaPanelLayout.createSequentialGroup()
                .addComponent(Panaller, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Kitaplar");

        jMenuItem1.setText("Kitaplari Goruntule");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Kitap Ara");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Hesabim");

        jMenuItem4.setText("Mevcut Kitaplarim");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Sifre Degis");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem3.setText("Cıkış");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAnaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAnaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    public void KitapListesiPaneliniOlustur(){
        DefaultTableModel model1 = (DefaultTableModel)tableKitap.getModel();
      DefaultTableModel model2 = (DefaultTableModel)tableBasili.getModel();
      DefaultTableModel model3 = (DefaultTableModel)tableEkitap.getModel();
      DefaultTableModel model4 = (DefaultTableModel)tableRoman.getModel();
      DefaultTableModel model5 = (DefaultTableModel)tableAnsiklopedi.getModel();
      DefaultTableModel model6 = (DefaultTableModel)tableDergi.getModel();
      
      int index = 0;
      
      while(InfoKitap.getKitapSize() > index){
      model1.addRow(new Object[]{kitap.get(index).getID(),kitap.get(index).getKitap_adi(),kitap.get(index).getYayim_Evi(),kitap.get(index).getBasim_tarihi()});
          index++;
          
      }
     index = 0;
      while(basili.size() > index){
       model2.addRow(new Object[]{basili.get(index).getID(),basili.get(index).getKitap_adi(),basili.get(index).getYayim_Evi(),basili.get(index).getBasim_tarihi()});
       index++;   
          
      }
      index = 0;
      while(elek.size() > index){
          
     model3.addRow(new Object[]{elek.get(index).getID(),elek.get(index).getKitap_adi(),elek.get(index).getYayim_Evi(),elek.get(index).getBasim_tarihi(),elek.get(index).getDil()});
          
     index++;
          
      }
      index = 0;
      while(roman.size() > index){
          
      model4.addRow(new Object[]{roman.get(index).getID(),roman.get(index).getKitap_adi(),roman.get(index).getYayim_Evi(),roman.get(index).getBasim_tarihi(),roman.get(index).getYazar(),roman.get(index).getTür()});
      index++;
      }
      index = 0;
     while(ansiklopedi.size() > index){
          
          model5.addRow(new Object[]{ansiklopedi.get(index).getID(),ansiklopedi.get(index).getKitap_adi(),ansiklopedi.get(index).getYayim_Evi(),ansiklopedi.get(index).getBasim_tarihi(),ansiklopedi.get(index).getKonu()});
          index++;
          
      }
      
      index = 0;
      while(dergi.size() > index){
          model6.addRow(new Object[]{dergi.get(index).getID(),dergi.get(index).getKitap_adi(),dergi.get(index).getYayim_Evi(),dergi.get(index).getBasim_tarihi(),dergi.get(index).getTürDergi(),dergi.get(index).getEditor()});
          index++;
      }
      index = 0;
    }
    public void KitapListesiPaneliBosalt(){
        
       
      DefaultTableModel model1 = (DefaultTableModel)tableKitap.getModel();
      DefaultTableModel model2 = (DefaultTableModel)tableBasili.getModel();
      DefaultTableModel model3 = (DefaultTableModel)tableEkitap.getModel();
      DefaultTableModel model4 = (DefaultTableModel)tableRoman.getModel();
      DefaultTableModel model5 = (DefaultTableModel)tableAnsiklopedi.getModel();
      DefaultTableModel model6 = (DefaultTableModel)tableDergi.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);
        model4.setRowCount(0);
        model5.setRowCount(0);
        model6.setRowCount(0);
        
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       KitapListesiPaneliBosalt();
       Panaller.setVisible(true);
      jpKitapList.setVisible(true);
      jpAramaPanelleri.setVisible(false);
      jPMevcutKitaplar.setVisible(false);
      jPHesabim.setVisible(false);
      jpSifreDegis.setVisible(false);
      KitapListesiPaneliniOlustur();
   
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void btnDahaFazlaBilgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDahaFazlaBilgActionPerformed
        int []indexs = new int[6];
        indexs[0] = tableKitap.getSelectedRow();
        indexs[1] = tableBasili.getSelectedRow();
        indexs[2] = tableEkitap.getSelectedRow();
        indexs[3] = tableRoman.getSelectedRow();
        indexs[4] = tableAnsiklopedi.getSelectedRow();
        indexs[5] = tableDergi.getSelectedRow();
        
        
       for (int i = 0; i <= 5; i++) {
            if (indexs[i] != -1) {
            switch (i){
                case 0:
               secilen = kitap.get(indexs[i]);
                    
               break;
                case 1 :
                secilen = basili.get(indexs[i]);
               
                break;
                case 2 :
                secilen = elek.get(indexs[i]);
               
                break;
                case 3 :
                secilen = roman.get(indexs[i]);
                
                break;
                case 4 : 
                secilen = ansiklopedi.get(indexs[i]);
                
                break;
                case 5 :
                secilen = dergi.get(indexs[i]);
               
                break;
                
                
            }
                   
                
            }
    
            
        }
        
       
        
      DahaFazla x = new DahaFazla(secilen);
        
   // this.setVisible(false);
     x.setVisible(true);
        //System.out.println("Selected index = " + tableKitap.getSelectedRow());
    }//GEN-LAST:event_btnDahaFazlaBilgActionPerformed

    private void panelShowAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelShowAllMouseClicked
        
    }//GEN-LAST:event_panelShowAllMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Panaller.setVisible(true);
        jpAramaPanelleri.setVisible(true);
        jpKitapList.setVisible(false);
        jPMevcutKitaplar.setVisible(false);
        jPHesabim.setVisible(false);
        jpSifreDegis.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jrKitapIDARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrKitapIDARAActionPerformed
       jpanelSecimler.setVisible(true);
       panelAdİleAra.setVisible(false);
       
       PanelIDileAra.setVisible(true);
       
    }//GEN-LAST:event_jrKitapIDARAActionPerformed

    private void jrKitapADIARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrKitapADIARAActionPerformed
        // TODO add your handling code here:
        jpanelSecimler.setVisible(true);
       panelAdİleAra.setVisible(true);
      
       PanelIDileAra.setVisible(false);
    }//GEN-LAST:event_jrKitapADIARAActionPerformed
int id;
    ArrayList<Kitap> arananKitapLar = new ArrayList<Kitap>();
    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
       Kitap aranacak = null;
       
        if (jrKitapIDARA.isSelected()) {
        aranacak = InfoKitap.KitapAra(Integer.parseInt(tfSearchedId.getText()));
        id = Integer.parseInt(tfSearchedId.getText());
        if (aranacak == null) {
           JOptionPane.showMessageDialog(null, "Aradiginiz Kitap Bulunamadi !!"); 
        }
        else{
            arananKitapLar.add(InfoKitap.KitapAra(Integer.parseInt(tfSearchedId.getText())));
        }
           
        }
        
        else if(jrKitapADIARA.isSelected()){
            aranacak = InfoKitap.KitapAra(tfSearchedName.getText());
            if (aranacak == null) {
           JOptionPane.showMessageDialog(null, "Aradiginiz Kitap Bulunamadi !!");
        }
            else{
                arananKitapLar.add(aranacak);
            }
        }
        
        
         if (aranacak == null) {
           JOptionPane.showMessageDialog(null, "Aradiginiz Kitap Bulunamadi !!");
        }
         
         
         else{
         DefaultTableModel model = (DefaultTableModel) tableAranan.getModel();
         String Tür = "";
         
             if (aranacak instanceof Roman) {
              Tür = "Roman";
              model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Roman) aranacak).getTür()});
             }
             else if(aranacak instanceof Dergi){
                 Tür = "Dergi";
                 model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Dergi) aranacak).getTürDergi()});
                 
             }
             else if(aranacak instanceof Ansiklopedi){
                 Tür = "Ansiklopedi";
                 model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Ansiklopedi) aranacak).getKonu()});
             }
             
         }
         
    }//GEN-LAST:event_btnAraActionPerformed

    public String SifreDondur(){
      
        return BaglananSifre;
    }
    public static Kitap aranankitapNe = null;
    private void btnOduncALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncALActionPerformed
        int index = tableAranan.getSelectedRow();
        
        if (index != -1) {
            aranankitapNe = arananKitapLar.get(index);
            if (InfoKitap.KitapOduncVer(aranankitapNe, InfoKullanici.KitapAlmakİsteyeniDondur(Giris.GirilenID, Giris.GirilenSifre))) {
                JOptionPane.showMessageDialog(null, "Kitap Alma İslemi Basarili");
            }
            else{
                JOptionPane.showMessageDialog(null, "Bu kitap Zaten Alinmistir !!");
            }
 
            
        }
        
    }//GEN-LAST:event_btnOduncALActionPerformed
public void close(Giris x){
    this.setVisible(false);
    x.setVisible(true);
}
 public void KitaplariDosyayaYaz() throws IOException{
     File f = new File("books.txt");
     FileWriter yaz = new FileWriter(f);
     ArrayList<Kitap> x = InfoKitap.getKitapListem();
        
     for(int i = 0 ; i< x.size();i++){
      if(x.get(i) instanceof Roman){
      if(x.get(i).isUygun()){
      yaz.write("r" + "," + ((Roman) x.get(i)).getTür() + "," + ((Roman) x.get(i)).getYaşAralığı() + "," + ((Roman) x.get(i)).getEtkilendiğiAkım() + "," + ((Roman) x.get(i)).getYazar()+","+((Roman) x.get(i)).getHamur()+ "," + ((Roman) x.get(i)).getBaskı() + "," + ((Roman) x.get(i)).getSize() + "," + x.get(i).getKitap_adi() + ","+ x.get(i).getBasim_tarihi() + "," + x.get(i).getYayim_Evi() + "," + x.get(i).getUrl() + "," + "true" + "\n" );
          
      }
      else{
       yaz.write("r" + "," + ((Roman) x.get(i)).getTür() + "," + ((Roman) x.get(i)).getYaşAralığı() + "," + ((Roman) x.get(i)).getEtkilendiğiAkım() + "," + ((Roman) x.get(i)).getYazar()+","+((Roman) x.get(i)).getHamur()+ "," + ((Roman) x.get(i)).getBaskı() + "," + ((Roman) x.get(i)).getSize() + "," + x.get(i).getKitap_adi() + ","+ x.get(i).getBasim_tarihi() + "," + x.get(i).getYayim_Evi() + "," + x.get(i).getUrl() + "," + "false" +"," + x.get(i).getKitapAlan().getAlanınAdi() +","+x.get(i).getKitapAlan().getAlaninSoyadi() + ","+ x.get(i).getKitapAlan().getBolum() + "," + x.get(i).getKitapAlan().getKullanici_id() + "," + x.get(i).getKitapAlan().getKullanici_parola() + "," + x.get(i).getKitapAlan().getTeslimTarihi()+ "\n");   
      }
          
      }   
      
      
      else if(x.get(i) instanceof Dergi){
         if(x.get(i).isUygun()){
          yaz.write("d" + ","+((Dergi) x.get(i)).getWebSayfasi()+","+((Dergi) x.get(i)).getTürDergi() + "," +((Dergi) x.get(i)).getEditor() + "," + ((Dergi) x.get(i)).getKoordinator() + "," + ((Dergi) x.get(i)).getSayi() + "," + ((Dergi) x.get(i)).getYayımAralığı() + "," + ((Dergi) x.get(i)).getBaskıElek() + "," + ((Dergi) x.get(i)).getDil() + "," + x.get(i).getKitap_adi() + "," + x.get(i).getBasim_tarihi() + "," + x.get(i).getYayim_Evi() + "," + x.get(i).getUrl() +","+ "true" + "\n");
      }
      else{
          yaz.write("d" + "," + ((Dergi) x.get(i)).getWebSayfasi()+","+ ((Dergi) x.get(i)).getTürDergi() + "," +((Dergi) x.get(i)).getEditor() + "," + ((Dergi) x.get(i)).getKoordinator() + "," + ((Dergi) x.get(i)).getSayi() + "," + ((Dergi) x.get(i)).getYayımAralığı() + "," + ((Dergi) x.get(i)).getBaskıElek() + "," + ((Dergi) x.get(i)).getDil() + "," + x.get(i).getKitap_adi() + "," + x.get(i).getBasim_tarihi() + "," + x.get(i).getYayim_Evi() + "," + x.get(i).getUrl() +","+ "false" + "," + x.get(i).getKitapAlan().getAlanınAdi() + "," + x.get(i).getKitapAlan().getAlaninSoyadi() + "," + x.get(i).getKitapAlan().getBolum() + "," + x.get(i).getKitapAlan().getKullanici_id() + "," + x.get(i).getKitapAlan().getKullanici_parola() + "," + x.get(i).getKitapAlan().getTeslimTarihi()+ "\n"); 
      }  
      }
      
      
      else if(x.get(i) instanceof Ansiklopedi){
         if(x.get(i).isUygun()){
         yaz.write("a" + "," +((Ansiklopedi) x.get(i)).getKonu() + "," + ((Ansiklopedi) x.get(i)).getContributors() + "," + ((Ansiklopedi) x.get(i)).getHamur() + "," + ((Ansiklopedi) x.get(i)).getBaskı() + "," + ((Ansiklopedi) x.get(i)).getSize()+ "," +x.get(i).getKitap_adi() +"," + x.get(i).getBasim_tarihi() + "," + x.get(i).getYayim_Evi() + "," +x.get(i).getUrl() + "," + "true" + "\n" );
      }
      else{
         yaz.write("a" + "," +((Ansiklopedi) x.get(i)).getKonu() + "," + ((Ansiklopedi) x.get(i)).getContributors() + "," + ((Ansiklopedi) x.get(i)).getHamur() + "," + ((Ansiklopedi) x.get(i)).getBaskı() + "," + ((Ansiklopedi) x.get(i)).getSize()+ "," +x.get(i).getKitap_adi() +"," + x.get(i).getBasim_tarihi() + "," + x.get(i).getYayim_Evi() + "," +x.get(i).getUrl() + "," + "false" + "," + x.get(i).getKitapAlan().getAlanınAdi() + "," + x.get(i).getKitapAlan().getAlaninSoyadi() + "," + x.get(i).getKitapAlan().getBolum() + "," + x.get(i).getKitapAlan().getKullanici_id() + "," + x.get(i).getKitapAlan().getKullanici_parola() + "," + x.get(i).getKitapAlan().getTeslimTarihi()+ "\n");  
      } 
         
      }   
     
      
      
     }
      yaz.close();
    }
  public void NormalKullanicilariDosyayaYaz() throws IOException{
    File f = new File("users.txt");
        FileWriter yaz = new FileWriter(f);
        ArrayList<Normal> x = InfoKullanici.getMyUsers();
        for(int i = 0; i<x.size(); i++){
           yaz.write(x.get(i).getAlanınAdi() + "," + x.get(i).getAlaninSoyadi() + "," + x.get(i).getBolum() + "," + x.get(i).getKullanici_id() + ","+x.get(i).getKullanici_parola()+ "\n"); 
        }
        yaz.close();
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        a.setVisible(true);
          try {
              KitaplariDosyayaYaz();
              NormalKullanicilariDosyayaYaz();
          } catch (IOException ex) {
              Logger.getLogger(Kullanici_GUI.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
public void MevcutKitaplariOlustur(){
     DefaultTableModel MODEL = (DefaultTableModel)jTableMevcutKitaplar.getModel();
        int index = 0;
       ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.GirilenID, Giris.GirilenSifre);
       String Tür = "";
       while(index < x.size()){
           if (x.get(index) instanceof Roman) {
               Tür = "Roman";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Roman) x.get(index)).getTür(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           else if (x.get(index) instanceof Dergi) {
               Tür = "Dergi";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Dergi) x.get(index)).getTürDergi(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           else if(x.get(index) instanceof Ansiklopedi){
               Tür = "Ansiklopedi";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Ansiklopedi) x.get(index)).getKonu(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           index++;
       }
}
public void MevcutKitaplariSil(){
    DefaultTableModel model = (DefaultTableModel) jTableMevcutKitaplar.getModel();
    model.setRowCount(0);
}
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         Panaller.setVisible(true);
        jpAramaPanelleri.setVisible(false);
        jpKitapList.setVisible(false);
        jPMevcutKitaplar.setVisible(true);
        jPHesabim.setVisible(false);
        jpSifreDegis.setVisible(false);
                
       /* DefaultTableModel MODEL = (DefaultTableModel)jTableMevcutKitaplar.getModel();
        int index = 0;
       ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.GirilenID, Giris.GirilenSifre);
       String Tür = "";
       while(index < x.size()){
           if (x.get(index) instanceof Roman) {
               Tür = "Roman";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Roman) x.get(index)).getTür(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           else if (x.get(index) instanceof Dergi) {
               Tür = "Dergi";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Dergi) x.get(index)).getTürDergi(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           else if(x.get(index) instanceof Ansiklopedi){
               Tür = "Ansiklopedi";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Ansiklopedi) x.get(index)).getKonu(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           index++;
       }
      
       /*if (aranacak instanceof Roman) {
              Tür = "Roman";
              model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Roman) aranacak).getTür()});
             }
             else if(aranacak instanceof Dergi){
                 Tür = "Dergi";
                 model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Dergi) aranacak).getTürDergi()});
                 
             }
             else if(aranacak instanceof Ansiklopedi){
                 Tür = "Ansiklopedi";
                 model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Ansiklopedi) aranacak).getKonu()});
             }*/
       MevcutKitaplariSil();
       MevcutKitaplariOlustur();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnDAHAFAZLAMEVCUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDAHAFAZLAMEVCUTActionPerformed
    int index = jTableMevcutKitaplar.getSelectedRow();
    DahaFazla abc;
    ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.GirilenID, Giris.GirilenSifre);
        if (index != -1) {
          abc = new DahaFazla(x.get(index));
          abc.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Lutfen Bir secim Yapiniz !!");
        }
    //DahaFazla zed = new DahaFazla();
    }//GEN-LAST:event_btnDAHAFAZLAMEVCUTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Kitap iadeEt;
       int index = jTableMevcutKitaplar.getSelectedRow();
        if (index != -1) {
          ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.GirilenID, Giris.GirilenSifre);
          iadeEt = x.get(index);
          InfoKitap.KitapGeriAl(iadeEt);
          
        JOptionPane.showMessageDialog(null, "Odunc Verme işlemi Başarili !!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Bir Hata İle Karşilasildi !!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Panaller.setVisible(true);
      jpKitapList.setVisible(false);
      jpAramaPanelleri.setVisible(false);
      jPMevcutKitaplar.setVisible(false);
      jPHesabim.setVisible(false);
      jpSifreDegis.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String x = String.valueOf(jPassEskiKullaniciSifre.getPassword());
        String y = String.valueOf(jPassYeniKullaniciSifre.getPassword());
        String z = String.valueOf(jPassYeniKullaniciSifre2.getPassword());
        
        if (x.equals(a.BaglananKullaniciParola())) {
            if (y.equals(z)) {
             int reply = JOptionPane.showConfirmDialog(null, "Sifreniz Degistirilecektir", "Emin Misiniz ?", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_NO_OPTION) {
                   InfoKullanici.KullaniciSifreDegis(a.BaglananKullaniciID(),a.BaglananKullaniciParola(), y);
                   JOptionPane.showMessageDialog(null, "Islem Basarili");
                }
                else{
                    JOptionPane.showMessageDialog(null, "İslem İptal Edildi");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Sifreler Uyusmuyor !");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Hatali Sifre");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panaller;
    private javax.swing.JPanel PanelIDileAra;
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnDAHAFAZLAMEVCUT;
    private javax.swing.JButton btnDahaFazlaBilg;
    private javax.swing.JButton btnOduncAL;
    private javax.swing.ButtonGroup buttonGroupArama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPHesabim;
    private javax.swing.JPanel jPMevcutKitaplar;
    private javax.swing.JPasswordField jPassEskiKullaniciSifre;
    private javax.swing.JPasswordField jPassYeniKullaniciSifre;
    private javax.swing.JPasswordField jPassYeniKullaniciSifre2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMevcutKitaplar;
    private javax.swing.JPanel jpAnaPanel;
    private javax.swing.JPanel jpAramaPanelleri;
    private javax.swing.JPanel jpKitapList;
    private javax.swing.JPanel jpSifreDegis;
    private javax.swing.JPanel jpanelSecimler;
    private javax.swing.JRadioButton jrKitapADIARA;
    private javax.swing.JRadioButton jrKitapIDARA;
    private javax.swing.JLabel lblMesaj;
    private javax.swing.JPanel panelAdİleAra;
    private javax.swing.JPanel panelShowAll;
    private javax.swing.JPanel panelShowAnsiklopedi;
    private javax.swing.JPanel panelShowBasili;
    private javax.swing.JPanel panelShowDergi;
    private javax.swing.JPanel panelShowEKitap;
    private javax.swing.JPanel panelShowRoman;
    private javax.swing.JTable tableAnsiklopedi;
    private javax.swing.JTable tableAranan;
    private javax.swing.JTable tableBasili;
    private javax.swing.JTable tableDergi;
    private javax.swing.JTable tableEkitap;
    private javax.swing.JTable tableKitap;
    private javax.swing.JTable tableRoman;
    private javax.swing.JTextField tfSearchedId;
    private javax.swing.JTextField tfSearchedName;
    // End of variables declaration//GEN-END:variables
}
